name: PrefixPro
version: '${project.version}'
main: com.samvolvo.prefixPro.PrefixPro
api-version: '1.20'
depend: [LuckPerms]
commands:
  prefixpro:
    description: Use the plugins pre-installed tools.
    usage: /prefixpro <option1> <option2>
permissions:
  prefixpro.reload:
    description: Can use the /prefixpro command
    default: false

