name: LuckpermsPrefix
version: '1.0-SNAPSHOT'
main: com.samvolvo.luckpermsPrefix.LuckpermsPrefix
api-version: '1.20'
depend: [LuckPerms]
commands:
  luckpermsprefix:
    description: Use the plugins pre-installed tools.
    usage: /luckpermsprefix reload <what>
permissions:
  luckpermsprefix.reload:
    description: Can use the /reloadprefix command
    default: false

