name: LuckpermsPrefix
version: '1.0-SNAPSHOT'
main: com.samvolvo.luckpermsPrefix.LuckpermsPrefix
api-version: '1.20'
depend: [LuckPerms]
commands:
  reloadprefix:
    description: Reload all prefixes of online players.
    permission: luckpermsprefix.reload
    usage: /reloadprefix
permissions:
  luckpermsprefix.reload:
    description: Can use the /reloadprefix command
    default: false

